script: clean config

diff --git a/script/2_init b/script/2_init
--- a/script/2_init
+++ b/script/2_init
@@ -1,5 +1,11 @@
 #! /bin/bash
 
+set -o errexit          # Exit on most errors (see the manual)
+set -o errtrace         # Make sure any error trap is inherited
+set -o nounset          # Disallow expansion of unset variables
+set -o pipefail         # Use last non-zero exit code in a pipeline
+set -o xtrace           # Trace the execution of the script (debug)
+
 if [ "`uname`" == "Linux" ]; then
   [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
   apt-get update
